admins can edit category
NSS-Day-Cohort-42/rare-fakes-news pull request #202
Opened 2020-11-17 21:25 UTC by esthersanders

Admin (only) can edit a category

## Description

on Category Management, an admin can edit a category

## Tickets
_My PR references these tickets (epic and task tickets)_

1. #117 Edit a Category
​

## How do I access this branch?

1. ```git fetch --all```
1. ```git checkout es-edit-category ``` 
1. have server branch checked out as well and ```python manage.py runserver``` 

​

​
## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing
- [x] Tested in Postman
- [x] Tested with Client

## To do
1. log in as an admin
1. go to Category Management and edit a category (verify these changes in postman)
1. log in as an author, verify that edit is not an option on Category Management
​

## Checklist for Reviewer
- [ ] check it out
- [ ] test all edge cases listed and more if you think of them (postman or browser)
- [ ] request changes/approve
- [ ] review code to make sure it fits coding style of project

2020-11-17 21:33 UTC, egeehartz approved these changes

2020-11-17 21:48 UTC, egeehartz requested changes
Take out localStorage.setItem

2020-11-17 21:51 UTC, Cwelshofer approved these changes
Everything looks good.

2020-11-18 16:34 UTC, egeehartz approved these changes

2020-11-18 16:37 UTC, Cwelshofer approved these changes
Everything works, looks good.

2020-11-18 16:38 UTC, merged